//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRS.Sync.Watcher.Linq.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_bjHappy;Integrated Security=True")]
        public string ipowdb_bjHappyConnectionString1 {
            get {
                return ((string)(this["ipowdb_bjHappyConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_bjHappy;User ID=sa")]
        public string ipowdb_bjHappyConnectionString2 {
            get {
                return ((string)(this["ipowdb_bjHappyConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_bjHappy;Persist Security Info=True;User ID=s" +
            "a")]
        public string ipowdb_bjHappyConnectionString3 {
            get {
                return ((string)(this["ipowdb_bjHappyConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_bjHappy;Persist Security Info=True;User ID=s" +
            "a")]
        public string ipowdb_bjHappyConnectionString4 {
            get {
                return ((string)(this["ipowdb_bjHappyConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_bjHappy;Persist Security Info=True;User ID=s" +
            "a;Password=sa")]
        public string ipowdb_bjHappyConnectionString {
            get {
                return ((string)(this["ipowdb_bjHappyConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_cldb;User ID=sa")]
        public string ipowdb_cldbConnectionString {
            get {
                return ((string)(this["ipowdb_cldbConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=ipowdb_cldb;Persist Security Info=True;User ID=sa")]
        public string ipowdb_cldbConnectionString1 {
            get {
                return ((string)(this["ipowdb_cldbConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.173;Initial Catalog=ipowdb_chuanloo;User ID=sa")]
        public string ipowdb_chuanlooConnectionString {
            get {
                return ((string)(this["ipowdb_chuanlooConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.173;Initial Catalog=ipowdb_chuanloo;Persist Security Info=T" +
            "rue;User ID=sa")]
        public string ipowdb_chuanlooConnectionString1 {
            get {
                return ((string)(this["ipowdb_chuanlooConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.173;Initial Catalog=ipowdb_chuanloo;User ID=sa;Password=sa")]
        public string ipowdb_chuanlooConnectionString2 {
            get {
                return ((string)(this["ipowdb_chuanlooConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.174;Initial Catalog=ipowdb_AdventureWaterWorld;Persist Secu" +
            "rity Info=True;User ID=sa")]
        public string ipowdb_AdventureWaterWorldConnectionString {
            get {
                return ((string)(this["ipowdb_AdventureWaterWorldConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.173;Initial Catalog=ipowdb_AdventureWaterWorld;Persist Secu" +
            "rity Info=True;User ID=sa")]
        public string ipowdb_AdventureWaterWorldConnectionString1 {
            get {
                return ((string)(this["ipowdb_AdventureWaterWorldConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.8.174;Initial Catalog=ipowdb_AdventureWaterWorld;User ID=sa")]
        public string ipowdb_AdventureWaterWorldConnectionString2 {
            get {
                return ((string)(this["ipowdb_AdventureWaterWorldConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=202.104.149.179\\MSSQL2012QY,1455;Initial Catalog=estay_ecs_1210;Persi" +
            "st Security Info=True;User ID=webApplication")]
        public string estay_ecs_1210ConnectionString {
            get {
                return ((string)(this["estay_ecs_1210ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=202.104.149.179\\MSSQL2012QY,1455;Initial Catalog=estay_ecs_1210;User " +
            "ID=webApplication")]
        public string estay_ecs_1210ConnectionString1 {
            get {
                return ((string)(this["estay_ecs_1210ConnectionString1"]));
            }
        }
    }
}
