//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : CRSInterFaceResult
	/// Data Source    : CRSInterFaceResult
	/// Server Version : 3.8.5
	/// </summary>
	public partial class CRSInterFaceResultDB : LinqToDB.Data.DataConnection
	{
		public ITable<RateCodeControl> RateCodeControls { get { return this.GetTable<RateCodeControl>(); } }
		public ITable<RateCodeInfor>   RateCodeInfors   { get { return this.GetTable<RateCodeInfor>(); } }
		public ITable<RoomRateW>       RoomRateWS       { get { return this.GetTable<RoomRateW>(); } }

		public CRSInterFaceResultDB()
		{
			InitDataContext();
		}

		public CRSInterFaceResultDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("RateCodeControl")]
	public partial class RateCodeControl
	{
		[Column, NotNull    ] public int    hotelId      { get; set; } // int
		[Column, NotNull    ] public string rateCode     { get; set; } // varchar(2147483647)
		[Column, NotNull    ] public string rmType       { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string amendStatus  { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?   amendDays    { get; set; } // int
		[Column,    Nullable] public int?   cancelStatus { get; set; } // int
		[Column,    Nullable] public int?   cancelDays   { get; set; } // int
		[Column,    Nullable] public string needPay      { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?   minStay      { get; set; } // int
		[Column,    Nullable] public int?   maxStay      { get; set; } // int
		[Column,    Nullable] public string booking      { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?   rmLimit      { get; set; } // int
	}

	[Table("RateCodeInfor")]
	public partial class RateCodeInfor
	{
		[Column, NotNull    ] public int    hotelId            { get; set; } // int
		[Column, NotNull    ] public string rateCode           { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string cName              { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string eName              { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string memberType         { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string cardType           { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string isContract         { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string currency           { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string rateCat            { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string begDate            { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string endDate            { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string isdiscount         { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string market             { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string source             { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string weekenddays        { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?   ptCoef             { get; set; } // int
		[Column,    Nullable] public string discountOf         { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string discountType       { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?   discountValue      { get; set; } // int
		[Column,    Nullable] public string roundType          { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string targetRound        { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string status             { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string defaultShow        { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string sellBegDate        { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string sellEndDate        { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string bookingThrough     { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string aliasCn            { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string aliasEn            { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?   contractId         { get; set; } // int
		[Column,    Nullable] public int?   dailyinvallocation { get; set; } // int
		[Column,    Nullable] public string descript           { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string edescript          { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string frtMarket          { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string frtSource          { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string isUpward           { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string remarks            { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string syncstatus         { get; set; } // varchar(2147483647)
	}

	[Table("RoomRateWS")]
	public partial class RoomRateW
	{
		[Column, NotNull    ] public int       hotelId        { get; set; } // int
		[Column,    Nullable] public string    rmTypeEName    { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    breakfastEDesc { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?      minVacRooms    { get; set; } // int
		[Column,    Nullable] public string    rateCodeCName  { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    rateCodeEName  { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    rmTypeEDesc    { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    ratePrice      { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    rateCode       { get; set; } // varchar(2147483647)
		[Column,    Nullable] public DateTime? rateDate       { get; set; } // date
		[Column,    Nullable] public string    rmType         { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    rmTypeCDesc    { get; set; } // varchar(2147483647)
		[Column,    Nullable] public string    rmTypeCName    { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?      vacRooms       { get; set; } // int
		[Column,    Nullable] public string    breakfastDesc  { get; set; } // varchar(2147483647)
		[Column,    Nullable] public int?      needPay        { get; set; } // int
		[Column,    Nullable] public int?      needGuarant    { get; set; } // int
	}
}
